# Fetching the minified node image on apline linux
FROM node:22-alpine

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

# Declaring env
ENV NODE_ENV=production

# Next.js on railway doesn't include .env at build time, need to copy some env vars
ARG NEXT_PUBLIC_NEYNAR_CLIENT_ID
ENV NEXT_PUBLIC_NEYNAR_CLIENT_ID $NEXT_PUBLIC_NEYNAR_CLIENT_ID

# Setting up the work directory
WORKDIR /app

# Copy the package.json, and yarn.lock files
COPY . .

# Installing dependencies
RUN pnpm install --production=false

# Add sharp from alpine image for nextjs image optimization
RUN cd apps/web && pnpm add sharp --production=false

# Build the web app
RUN pnpm build:web

# Set port provided by railway
ARG PORT

# Expose the port 
EXPOSE $PORT

CMD ["sh", "-c", "sleep 3 && pnpm start:web"]